import camelCase from 'lodash/camelCase';
export const SALES_SUBSECTOR = 'Sales, Accounts & Customer Success';
export const MARKETING_SUBSECTOR = 'Marketing, Community & PR';
export const OPERATIONS_SUBSECTOR = 'Operations, Strategy, Finance & Management';
export const RECRUITING_SUBSECTOR = 'Recruiting & HR';

export const FILTERS = {
  subSector: 'sub_sector',
  idealRoleTagVerified: 'ideal_role_tag_verified',
  idealRole: 'ideal_role',
  yearsOfExperience: 'years_of_experience',
  salary: 'salary_expectations_base',
  salaryOTE: 'salary_expectations_ote',
  salesSkills: 'sales_skills',
  operationsSkills: 'operations_skills',
  marketingSkills: 'marketing_skills',
  inHouseOrAgency: 'in_house_or_agency',
  workedAt: 'worked_at',
  salesDealSize: 'sales_deal_size',
  cv: 'cv',
  linkedinLink: 'linkedin_link',
  jobTitle: 'job_title',
  orgName: 'org_name',
  jobSummary: 'job_summary',
  pastOrganisation: 'past_organisation',
  salesPreferences: 'sales_preferences',
  citizenship: 'citizenship',
  picture: 'picture',
  name: 'name',
  email: 'email',
  phone: 'phone',
  visaType: 'visa_type',
  visaExpirationDate: 'visa_expiration_date',
  interestedLocations: 'interested_locations',
  offersStartDate: 'offers_start_date',
  unwantedCompanies: 'unwanted_companies',
  openPrivate: 'open_private',
  nativeLanguage: 'native_language',
  marketingBudget: 'marketing_budget',
  annualSalesQuota: 'annual_sales_quota',
  percentageOfQuota: 'percentage_of_quota',
  query: 'query',
  firstName: 'first_name',
  lastName: 'last_name',
  saasSalesSkills: 'saas_sales_skills',
  coldCallingPlays: 'cold_calling_plays',
  coldCallDrivenRole: 'cold_call_driven_role',
  inOutboundSales: 'in_outbound_sales',
  contentPiece: 'content_piece',
  btobBtocMarketing: 'btob_btoc_marketing',
  mobileAppMarketing: 'mobile_app_marketing',
  salesDealSizeCurrency: 'sales_deal_size_currency',
  annualSalesQuotaCurrency: 'annual_sales_quota_currency',
  marketingBudgetCurrency: 'marketing_budget_currency',
  currentLocation: 'current_location',
  password: 'password',
  howFoundOut: 'how_found_out',
  howFoundOutDetails: 'how_found_out_details',
  howFoundOutDetailsOther: 'how_found_out_details_other',
  idealRoleTagSales: 'ideal_role_tag_sales',
  idealRoleTagMarketing: 'ideal_role_tag_marketing',
  idealRoleTagOperations: 'ideal_role_tag_operations',
  idealRoleTagRecruiting: 'ideal_role_tag_recruiting',
  marketingSkillsCustom: 'marketing_skills_custom',
  operationsSkillsCustom: 'operations_skills_custom',
  interestedLocationsCustom: 'interested_locations_custom',
  completed: 'completed',
  referrer: 'referrer',
};

export const FILTERS_CAMELCASED = Object.keys(FILTERS).reduce((obj, key) => {
  obj[key] = camelCase(FILTERS[key]); // eslint-disable-line no-param-reassign
  return obj;
}, {});
